### ISSUE TITLE
Feature/Idea

### ISSUE THREAD

**Issue by AntoineDao** [ladybug-tools/artwork#1]
Can we make emoji versions of the bugs? 🐞 🐝 🦋 🐉 🕷

**Comment by mostaphaRoudsari** [comment]
Have you used any apps to do that? Is it just an image with converted to an emoji. I can Google this but I wonder if you have already done that before?

**Comment by AntoineDao** [comment]
I have never done it nor heard of it being done. I just really want it! 😛

**Comment by theo-armour** [comment]
See https://github.com/afeld/emoji-css/

We could build a style sheet that incorporated the Ladybug Tools mascots as well as any other useful symbols,

My question: Where - to what documents - could we apply the style sheet in an ongoing useful manner?

Or would it just be fun to have one?

**Comment by mostaphaRoudsari** [comment]
> Where - to what documents - could we apply the style sheet in an ongoing useful manner?

Not sure if there is a useful case for using emojis which cannot be replaced by a small image.

We can use it in our website and GitHub posts but I assume it will be mostly for fun. @AntoineDao, your thoughts on this?

**Comment by AntoineDao** [comment]
Yep defo just for fun. If anything could be extra nice to have as part of cloud service job tagging 😄

**Comment by chriswmackey** [comment]
I couldn't resist taking an hour to play around with this and I'm happy to put up a proof-of-concept for Ladybug Tools CSS Emojis:
http://www.ladybug.tools/artwork/logos/emojis/ladybug-emoji.html

I think I could pretty easily write a script to make emojis of all the component icons using the same code that @mostaphaRoudsari uses to make the Ladybug and Honeybee primers.

If I had to say the place that I would really want to use these icons, it would be on the discourse forum.  I can't describe how much of my life has been spent typing out the full names of components instead of just copying icons from a table like the one I linked to above.

The question would be: can we easily link a CSS stylesheet globally to the entire discourse forum?  I have to imagine that there mus t be some global stylesheets for the forum already.  If we could just link this one in, we can likely get a forum filled with custom emojis!

**Comment by AntoineDao** [comment]
So much yes for this! Thanks @chriswmackey!

**Comment by mostaphaRoudsari** [comment]
This is very cool. Still not sure where it will be useful but it is definitely fun!

> If I had to say the place that I would really want to use these icons, it would be on the discourse forum. I can't describe how much of my life has been spent typing out the full names of components instead of just copying icons from a table like the one I linked to above.

Not sure how the icons will address this issue but in any case...

> can we easily link a CSS stylesheet globally to the entire discourse forum? I have to imagine that there mus t be some global stylesheets for the forum already. If we could just link this one in, we can likely get a forum filled with custom emojis!

Yes. There is one! I followed the instruction and added a link to css file but it doesn't render correctly. You should be able to see the link if you open any page on discourse.

![image](https://user-images.githubusercontent.com/2915573/49699581-e0397080-fba0-11e8-92e4-fbf3ae5a9a71.png)

**Comment by chriswmackey** [comment]
Awesome! Thanks for doing that @mostaphaRoudsari .  It looks like we might have to whitelist some of the html tags:
https://meta.discourse.org/t/whitelisting-some-html-tags/24280/2

I'll investigate a bit more when I get some time.

I am just thinking that I can use emojis to reference certain components on the forum rather than writing out the full component name.

**Comment by mostaphaRoudsari** [comment]
Nice find! Or as [suggested on the same post](https://meta.discourse.org/t/whitelisting-some-html-tags/24280/4) we can develop a plugin like [this one](https://github.com/discourse/evolve_emoji). It will work on the forum and all we need is to [map keywords to png images](https://github.com/discourse/evolve_emoji/blob/master/assets/javascripts/evolve-emoji.js) which are already created for gitbooks.

**Comment by chriswmackey** [comment]
@mostapharoudsari ,

Yea, I was checking out that plugin and it looks very simple.  We could easily recreate it for Ladybug Tools.  

I was also thinking about it a little more and, given that we are remaking the components for [+], it might be a better idea to have the plugin reference the component icon pngs on this artwork repository rather than the gitbook repo. I know that, already, you have re-purposed some of the original component icons for other [+] components (like the legacy rendered animation component is now an annual image-based analysis component if I am not mistaken).  So, if we want to have an official lexicon of emojis that stands the test of time, it makes sense that they reference the new plugin rather than the old ones.

Let me know your thoughts here and I can have a go at making a plugin.

**Comment by mostaphaRoudsari** [comment]
since I was behind updating discourse and had it on my list I did start testing a minimal version of the plugin. let's see if it works before getting into details. Not sure if we need every single component but we can have them if useful! for now let's see if it will work...

https://github.com/ladybug-tools/ladybug_tools_discourse_emoji

**Comment by chriswmackey** [comment]
Ah, ok.  I was wondering why our forum was momentarily down.  

I agree we should start small with emojis and we should not rush to make an emoji for every component at the start.  We can make ones for the major components and then add more as we see fit.  I am just thinking that we may eventually want a script to build all of the emojis for us from a folder of pngs.

**Comment by chriswmackey** [comment]
BTW, I also found this:
https://meta.discourse.org/t/configure-custom-emoji/23365

It seems discourse might have some code already built into it to make custom emojis.

**Comment by mostaphaRoudsari** [comment]
UPDATE:

bad news: Trying to get the plugin(s) to work failed!

good news: At the same time from the link that @chriswmackey shared we can drag and drop all the icons as images into the page and we will have them as emojis in discourse! Easy and straight forward.

![](https://lh3.googleusercontent.com/-qKRsjC7Bog0/XA3aVVpepFI/AAAAAAAALjM/xSp2aneJ8VkOFCyW0hxhTTrOqqTg2HrVgCL0BGAYYCw/h761/2018-12-09.png)

**Comment by AntoineDao** [comment]
I guess this pretty much closes this issue right? Works on discourse and there's a CSS sheet in the wild that can be used in other contexts. Glad you all moved so quickly on this high priority issue 😄

**Comment by mostaphaRoudsari** [comment]
It feels good that you closed it. I felt super guilty last night for spending time on this but I can't lie, using them as emojis is really fun! 😄

**Comment by chriswmackey** [comment]
Yes, thank you for closing it @AntoineDao .  I don't know what it is about emojis that is so addicting.

And, even though it did take a few hours, one generally good thing that came out of all of this is that it definitely helped structure the files on this artwork repo a lot better and more reusably.  Our management of icons for [+] is going to be a lot better than legacy.

**Comment by AntoineDao** [comment]
Glad my unreasonable requirements could help 😄

**Comment by chriswmackey** [comment]
Finally closing out of this for sure.  I just wanted to say that I added documentation for contributing icons to this repo:
https://github.com/ladybug-tools/artwork/wiki/How-to-Contribute-New-Icons

And I switched over the web page that was previously for CSS icons to be for the markdown emojis on our forum:
https://www.ladybug.tools/artwork/emoji_webpage/ladybug-emoji.html
